Revert to "Remove code redundant with Block.validate_data_info"
This reverts commit a68d56a5d6063759264957944586b90f984f85c4.

remove the most recent commit, which failed the github actions test for
mysterious reasons

(the error was

ERROR: file or directory not found: testing/test_cde_inputs.py

no tests ran in 0.00s
Error: Process completed with exit code 4.

which is mysterious to me because I thought pytest should just be
looking for every test file in the testing directory)